---

apiVersion: v1
kind: Namespace
metadata:
  name: klum

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: klum
  namespace: klum
spec:
  replicas: 1
  selector:
    matchLabels:
      run: klum
  template:
    metadata:
      labels:
        run: klum
    spec:
      serviceAccountName: klum
      containers:
      - image: ibuildthecloud/klum:v0.1.0-amd64
        name: klum

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: klum
  namespace: klum

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: klum-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: klum
  namespace: klum
